export const clanovi = [
    {
        id: 1,
        ime: 'Luka',
        prezime: 'Hlavati',
        email: 'luka.hlavati@gmail.com',
        kontaktBroj: '0912345678',
    },
    {
        id: 2,
        ime: 'Marko',
        prezime: 'Horvat',
        email: 'marko.horvat@gmail.com',
        kontaktBroj: '0921234567',
    },
    {
        id: 3,
        ime: 'Ivana',
        prezime: 'Kovač',
        email: 'ivana.kovac@gmail.com',
        kontaktBroj: '0913456789',
    },
    {
        id: 4,
        ime: 'Petra',
        prezime: 'Babić',
        email: 'petra.babic@gmail.com',
        kontaktBroj: '0954567890',
    },
    {
        id: 5,
        ime: 'Tomislav',
        prezime: 'Jurić',
        email: 'tomislav.juric@gmail.com',
        kontaktBroj: '0995678901',
    },
    {
        id: 6,
        ime: 'Ana',
        prezime: 'Blažević',
        email: 'ana.blazevic@gmail.com',
        kontaktBroj: '0916789012',
    },
    {
        id: 7,
        ime: 'Nikola',
        prezime: 'Marić',
        email: 'nikola.maric@gmail.com',
        kontaktBroj: '0917890123',
    },
    {
        id: 8,
        ime: 'Sara',
        prezime: 'Petrović',
        email: 'sara.petrovic@gmail.com',
        kontaktBroj: '0918901234',
    },
];
