export const sportovi = [
    { sifra: 1, naziv: 'Nogomet', vrstaTerena: 'trava' },
    { sifra: 2, naziv: 'Tenis', vrstaTerena: 'zemlja' },
    { sifra: 3, naziv: 'Padel', vrstaTerena: 'trava' },
    { sifra: 4, naziv: 'Mali Nogomet', vrstaTerena: 'parket' },
    { sifra: 5, naziv: 'Košarka', vrstaTerena: 'parket' },
    { sifra: 6, naziv: 'Odbojka', vrstaTerena: 'parket' },
    { sifra: 7, naziv: 'Rukomet', vrstaTerena: 'parket' },
    { sifra: 8, naziv: 'Vaterpolo', vrstaTerena: 'voda' },
    { sifra: 9, naziv: 'Plivanje', vrstaTerena: 'voda' },
    { sifra: 10, naziv: 'Odbojka na pijesku', vrstaTerena: 'pijesak' },
    { sifra: 11, naziv: 'Stolni tenis', vrstaTerena: 'stol' },
    { sifra: 12, naziv: 'Badminton', vrstaTerena: 'parket' },
    { sifra: 13, naziv: 'Boks', vrstaTerena: 'ring' },
    { sifra: 14, naziv: 'Judo', vrstaTerena: 'tatami' },
    { sifra: 15, naziv: 'Američki nogomet', vrstaTerena: 'trava' },
    { sifra: 16, naziv: 'Bejzbol', vrstaTerena: 'pijesak/trava' },
    { sifra: 17, naziv: 'Hokej na ledu', vrstaTerena: 'led' },
    { sifra: 18, naziv: 'Golf', vrstaTerena: 'trava' },
    { sifra: 19, naziv: 'Skvoš', vrstaTerena: 'parket' },
    { sifra: 20, naziv: 'Kuglanje', vrstaTerena: 'staza' }
];